{% set name = "croniter" %}
{% set version = "0.3.35" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9075573d9d18fdc4c67ad6741c4bfa4b446b1b1d7f03279757244c8a75abedf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - natsort

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytz
    - tzlocal
  imports:
    - croniter
  commands:
    - python -m pip check
    - python -m pytest --pyargs croniter --cov croniter --cov-fail-under 86

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_file: mit.txt
  summary: croniter provides iteration for datetime object with cron like format
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
    - bollwyvl
