{% set name = "croniter" %}
{% set version = "0.3.36" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d3098e50f7edc7480470455d42f09c501fa1bb7e2fc113526ec6e90b068f32c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - natsort

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytz
    - tzlocal
  imports:
    - croniter
  commands:
    - python -m pip check
    - python -m pytest --pyargs croniter --cov croniter --cov-fail-under 86

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_file: mit.txt
  summary: croniter provides iteration for datetime object with cron like format
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
    - bollwyvl
